### ISSUE TITLE
Wemos Low power operation

### ISSUE THREAD

**Issue by suysh** [costastf/micropython_hourly_sleeper_library#2]
Hello,
Sorry to contact you in this way, but I'm having a question related to your hourly sleeper function.
I'm still searching for micropython code to apply on a Wemos D1 board with the lowest current with limited WLAN mqtt support.
My board is battery operated and using deepsleep with success, but I like to wake-up without WLAN and only enable when I need to transmit mqtt messages. In this way limit power consumption. I enable and disable the WLAN in my code before and after tranmitting mqtt.
I tried many configurations and my findings are that no matter how many hourly sleeps I put in (without WLAN communication), the battery is running down at the same speed.
I would expect that if I set the hourlysleeper to 24 hours (mqtt every day) that this uses less power than transmitting every hour. But, the voltage drop down of my battery doesn't show any difference between daily and hourly posting.
Do you have any idea why?
Kind regards, Hans

**Comment by costastf** [comment]
Hi Hans, don't worry, its no problem for me that you created an issue, but sadly i can't really help. From your description the only thing i can think of is that you do not successfully disable the WLAN so it does kickstart every time even though you don't send a message. Other than that I cannot really imagine what might be wrong. Although i wrote this library, i have not really done any work on low power usage of wemos boards since in my usage cases i am using power adapters and have things plugged in all the time. Sorry for not being able to help more.
